name: cartoon-animation-worker-ultra-hq
description: "Generate ULTRA HIGH QUALITY 1024x1024 cartoon character animations with voice using Dia TTS and AnimateDiff - Maximum Quality Mode"
version: "3.0.0"

runtime:
  python_version: "3.10"
  cuda_version: "12.1"

build:
  dockerfile: Dockerfile
  context: .

deployment:
  min_workers: 0
  max_workers: 1
  idle_timeout: 600  # Longer timeout for 1024x1024 generation
  
resources:
  gpu_types:
    - "A100"       # 80GB VRAM - REQUIRED for 1024x1024
    - "RTX A6000"  # 48GB VRAM - RECOMMENDED  
    - "H100"       # 80GB VRAM - EXCELLENT
  gpu_count: 1
  cpu_count: 16     # More CPU power for 1024x1024
  memory_gb: 128    # Maximum RAM for ultra quality
  disk_gb: 200      # More space for 1024x1024 outputs

environment:
  PYTHONPATH: "/workspace"
  RUNPOD_DEBUG: "false"
  ULTRA_QUALITY_MODE: "true"
  RESOLUTION_1024: "true"

handler:
  file: "handler.py"
  function: "generate_cartoon" 