name: cartoon-animation-worker
description: "Generate cartoon character animations with voice using Dia TTS and AnimateDiff"
version: "1.0.0"

runtime:
  python_version: "3.10"
  cuda_version: "12.1"

build:
  dockerfile: Dockerfile
  context: .

deployment:
  min_workers: 0
  max_workers: 1
  idle_timeout: 300
  
resources:
  gpu_types:
    - "RTX A6000"
    - "RTX 4090" 
    - "RTX 3090"
    - "A40"
  gpu_count: 1
  cpu_count: 8
  memory_gb: 32
  disk_gb: 50

environment:
  PYTHONPATH: "/workspace"
  RUNPOD_DEBUG: "false"

handler:
  file: "handler.py"
  function: "handler" 